### ISSUE TITLE
Problem with authentication to Baculum API

### ISSUE THREAD

**Issue by 4ss3g4f** [fametec/bacula#12]
![image](https://user-images.githubusercontent.com/22811935/89478674-d5424380-d7ba-11ea-976f-34104eae3b0f.png)

**Comment by MaoX17** [comment]
I have solved.

Go to your baculum container (console bin/bash) and run: 
ln -s /opt/bacula/etc /etc/bacula
and
chmod -R 777 /etc/bacula

now browse to http://ip.addr.es:9096
login with admin/admin

and follow all steps

Last step permit to change your api password

Come back to 
http://ip.addr.es:9095
go to setting
and set your new username/password

Now it work

**Comment by eduardofraga** [comment]
`chmod -R a+rwx etc/baculum`
