### ISSUE TITLE
Can you please provide some description of your containers?

### ISSUE THREAD

**Issue by ovizii** [fametec/bacula#13]
I am new to bacula and wanting to test it with docker. I can't find much on this standalone image, does this one contain all the other ones? 

Does this mean that instead of using say this docker-compose file: https://github.com/fametec/bacula/blob/master/docker/docker-compose.yml I could use this one: https://github.com/fametec/bacula/blob/master/docker/docker-compose-standalone-build.yml ?

**Comment by micter59** [comment]
I agree with this comment. It's really kind to provide these files, but it's not very useful without any documentation. Maybe you could provide some basic conf file, just to start everything. Anyway, thanks for your work.
