### ISSUE TITLE
Standalone baculum doesn't see the configuration

### ISSUE THREAD

**Issue by kocio-pl** [fametec/bacula#15]
Hi,
After running standalone of a current version version (9.6.5) by:

`docker-compose -f docker-compose-standalone-build.yml up -d`

and pointing web viewer to http://bacula:9095 I get some errors about config not being available to the web server. I fixed it by:

```
docker exec -it docker_bacula-standalone_1 bash
cd /etc
chgrp -R apache baculum
chmod -R 775 baculum
```

also in the "Config API" the first item ("Baculum working directory for Bacula config: /opt/bacula/etc") there was a problem, which I fixed in a similar way:

```
docker exec -it docker_bacula-standalone_1 bash
cd /opt/bacula
chgrp -R apache etc
chmod -R 775 etc
```

Now the baculum works, so I guess you should check if these problems are replicable.

**Comment by eduardofraga** [comment]
@eduardofraga
Create docker-compose-standalone.yaml
