### ISSUE TITLE
Erro no backup do Catalogo

### ISSUE THREAD

**Issue by cmenegotto** [fametec/bacula#17]
Ao executar o backup do catalogo o backup é executado com aviso.  
"Could not stat "/opt/bacula/working/bacula.sql": ERR=No such file or directory".

![image](https://user-images.githubusercontent.com/75267880/100637935-3239aa80-3312-11eb-9123-304178c27eda.png)

Abaixo segue a configuração do docker-compose.yml com acesso ao container do banco de dados.

![image](https://user-images.githubusercontent.com/75267880/100638140-7167fb80-3312-11eb-9a99-dc11b8980f0d.png)

**Comment by amauryeuzebio** [comment]
Boa noite.

Esse problema é por conta que as configurações RunBeforeJob e RunAfterJob são executados no container do bacula-dir e no momento da copia configurado no FileSert ele procura no container bacula-fd dessa forma para resolver esse problema basta trocar:
 
 RunBeforeJob = "/opt/bacula/scripts/make_catalog_backup.pl MyCatalog"  
 RunAfterJob  = "/opt/bacula/scripts/delete_catalog_backup"

 por 

 ClientRunBeforeJob = "/opt/bacula/scripts/make_catalog_backup.pl MyCatalog"
 ClientRunAfterJob = "/opt/bacula/scripts/delete_catalog_backup"

**Comment by eduardofraga** [comment]
Me envie o seu pull request para que eu possa dar o merge aqui.
