### ISSUE TITLE
Docker-compose error manifest unknown

### ISSUE THREAD

**Issue by melanysoft** [fametec/bacula#22]
Lates version 11.0.2 seems to have issues with image manifest.
Running 

> docker-compose up

results in error 

> ERROR: manifest for fametec/bacula-catalog:11.0.2 not found: manifest unknown: manifest unknown

**Comment by afernandez2000** [comment]
Yes images are not present in the DockerHub I tried to use the docker-compose-with-build but there is an issue with the bacula-postgresql depending on /bin/dash package that doesnt exists

**Comment by eduardofraga** [comment]
Change centos8 to centos7 and add epel-release
