### ISSUE TITLE
Can the UTF-8 encoding standard be used?

### ISSUE THREAD

**Issue by columbiana** [fametec/bacula#33]
Instead of your default database (SQL_ASCII), I created a new UTF8 database on a remote server. I did pg_dump from container docker_db_1 and pg_restore to my UTF8 database. And when I start a Job and Add a new client I get the following warning (as in the picture below):
 `bacula-dir JobId 0: Warning: Encoding error for database "sef". Wanted SQL_ASCII, got UTF8`
Are there any consequences in the future?

Thanks.

![pic1](https://user-images.githubusercontent.com/56273247/119331080-39b98b00-bc87-11eb-8916-a0ad9d2aae3d.PNG)

**Comment by eduardofraga** [comment]
Start a database with --encoding=SQL_ASCII --lc-collate=C --lc-ctype=C

And use the /opt/bacula/scripts/make_postgresql_tables and /opt/bacula/scripts/grant_postgresql_privileges to create a new catalog.
