### ISSUE TITLE
Error Error 1000: Internal error. [Warning] 

### ISSUE THREAD

**Issue by columbiana** [fametec/bacula#34]
When I want to add a new Fileset, I get the next error. The same goes if I try to add a pool, job ...

`Error Error 1000: Internal error. [Warning] file_put_contents(/opt/bacula/etc/bacula-dir.conf): failed to open stream: Permission denied (@line 58 in file /usr/share/baculum/htdocs/protected/Common/Class/ConfigBacula.php).`

![pic1](https://user-images.githubusercontent.com/56273247/119507580-3dc0d800-bd6f-11eb-9d70-6ace5392d260.PNG)

**Comment by eduardofraga** [comment]
Try to add a volume 


    volumes:
      
      
              - <span class="pl-s">./etc:/opt/bacula/etc:ro</span>
