### ISSUE TITLE
"Could not stat "/opt/bacula/working/bacula.sql": ERR=No such file or directory".

### ISSUE THREAD

**Issue by eduardofraga** [fametec/bacula#4]
Giovanni Grimaldi Torellyhá 11 dias
Erro no backup do catálogo

Olá!

Na imagem docker disponibilizada, ao tentar fazer o backup do catálogo, dá erro com o pg_dump.

Após algumas pesquisas, notei que para resolver, precisa fazer downgrade do PostgreSQL para a versão 9.2, o que resolve este problema.

Porém, me deparei com outro problema, após a execução do pg_dump: ele cria, corretamente, o arquivo, porém o Bacula não consegue incluí-lo, gerando o erro:

"Could not stat "/opt/bacula/working/bacula.sql": ERR=No such file or directory".

Infelizmente, ainda não encontrei um meio de resolver esse problema... alguém mais passou por isso?

**Comment by eduardofraga** [comment]
# Upgrade pg_dump

## Display currently version

`pg_dump --version`

    pg_dump (PostgreSQL) 9.2.24


## Install Repository 

`rpm -i https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm`


## Install Postgresql 9.4

`yum install postgresql94 -y`


## Remove Postgresql 9.2

`yum remove postgresql`


## Reinstall Postgresql 9.4

`yum reinstall postgresql94 -y`


## Display new version

`pg_dump --version`

    pg_dump (PostgreSQL) 9.4.25




# Referencies 

## https://yum.postgresql.org/repopackages.php

**Comment by eduardofraga** [comment]
Commit 2019120801

**Comment by amauryeuzebio** [comment]
Boa noite.

Esse problema é por conta que as configurações RunBeforeJob e RunAfterJob são executados no container do bacula-dir e no momento da copia configurado no FileSert ele procura no container bacula-fd dessa forma para resolver esse problema basta trocar:

RunBeforeJob = "/opt/bacula/scripts/make_catalog_backup.pl MyCatalog"
RunAfterJob = "/opt/bacula/scripts/delete_catalog_backup"

por

ClientRunBeforeJob = "/opt/bacula/scripts/make_catalog_backup.pl MyCatalog"
ClientRunAfterJob = "/opt/bacula/scripts/delete_catalog_backup"
